# Generated by Django 5.0.6 on 2024-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='delta',
            name='detail',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='delta',
            name='idea',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='delta',
            name='picture',
            field=models.ImageField(default='default_value', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='delta',
            name='profile',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='delta',
            name='studyTime',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='delta',
            name='title',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
